multipass: true

plugins:
  - cleanupAttrs: true
  - inlineStyles:
      onlyMatchedOnce: false
      removeMatchedSelectors: true
  - removeDoctype: true
  - removeXMLProcInst: true
  - removeComments: true
  - removeMetadata: true
  - removeTitle: true
  - removeDesc: true
  - removeUselessDefs: true
  - removeXMLNS: false
  - removeEditorsNSData: true
  - removeEmptyAttrs: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - removeEmptyContainers: true
  - removeViewBox: true
  - cleanupEnableBackground: true
  - minifyStyles: true
  - convertStyleToAttrs: true
  - convertColors: true
  - convertPathData: true
  - convertTransform: true
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: true
  - removeUnusedNS: true
  - prefixIds: false
  - cleanupIDs: false
  - cleanupNumericValues: false
  - cleanupListOfValues: false
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: true
  - removeRasterImages: false
  - mergePaths: true
  - convertShapeToPath: true
  - convertEllipseToCircle: true
  - sortAttrs: false
  - sortDefsChildren: false
  - removeDimensions: false
  - removeAttrs: false
  - removeAttributesBySelector: false
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - addAttributesToSVGElement: false
  - removeOffCanvasPaths: false
  - removeStyleElement: false
  - removeScriptElement: false
  - reusePaths: false

js2svg:
  pretty: true
  indent: '  '