/**
 * ATVA ACTUATORS L/H SIDE DATA MODEL:
 *
 * {
 *   id: ID matching the one in the SVG file,
 *   text: text to be used if item is shown in menu,
 *   unit: relative path to unit file on the right,
 *   desc: relative path to desc file on the left,
 *   info: {
 *     path: "./path/to/file.html",
 *     mode: "INLINE" | "POPUP" | "LINK",
 *     title: "Title" (popup only),
 *     size: "size-1" | "size-2" | "size-3" | "size-4" (popup only)
 *   }
 *   access:  {
 *     path: "./path/to/file.html",
 *     mode: "INLINE" | "POPUP" | "LINK",
 *     title: "Title" (popup only),
 *     size: "size-1" | "size-2" | "size-3" | "size-4" (popup only)
 *   },
 *   show_in_search: flag if this item is in search or only in SVG,
 * }
 */
export const DATA_SET_LH_SIDE = [
  {
    id: "clp-235dz",
    text: "235dz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceilingpanel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-235ez",
    text: "235ez",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-231kz",
    text: "231kz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-131hz",
    text: "131hz",
    unit: "./units/cabin/units/floor_panel.html",
    desc: "./units/cabin/desc/floor_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-131jz",
    text: "131jz",
    unit: "./units/cabin/units/floor_panel.html",
    desc: "./units/cabin/desc/floor_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-141az",
    text: "141az",
    unit: "./units/cabin/units/floor_panel.html",
    desc: "./units/cabin/desc/floor_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-241az",
    text: "241az",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-241cz",
    text: "241cz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-231mz",
    text: "231mz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-32-actuator",
    text: "32",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-37-actuator",
    text: "37",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-36-actuator",
    text: "36",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-35-actuator",
    text: "35",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-34-actuator",
    text: "34",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-33-actuator",
    text: "33",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-31-actuator",
    text: "31",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-27-actuator",
    text: "27",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-28-actuator",
    text: "28",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-25-actuator",
    text: "25",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-26-actuator",
    text: "26",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-30-actuator",
    text: "30",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-29-actuator",
    text: "29",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
];

/**
 * ATVA ACTUATORS L/H SIDE SVG FROM:
 *
 * Path to ATVA Actuators' interactive SVG file from left perspective.
 */
export const SVG_PATH_LH_SIDE = "./apps/anvs/config/atva-actuators/pic/lh-side.svg";

/**
 * ATVA ACTUATORS R/H SIDE DATA MODEL:
 *
 * {
 *   id: ID matching the one in the SVG file,
 *   text: text to be used if item is shown in menu,
 *   unit: relative path to unit file on the right,
 *   desc: relative path to desc file on the left,
 *   info: {
 *     path: "./path/to/file.html",
 *     mode: "INLINE" | "POPUP" | "LINK",
 *     title: "Title" (popup only),
 *     size: "size-1" | "size-2" | "size-3" | "size-4" (popup only)
 *   }
 *   access:  {
 *     path: "./path/to/file.html",
 *     mode: "INLINE" | "POPUP" | "LINK",
 *     title: "Title" (popup only),
 *     size: "size-1" | "size-2" | "size-3" | "size-4" (popup only)
 *   }
 * }
 */
export const DATA_SET_RH_SIDE = [
  {
    id: "clp-245bz",
    text: "245bz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-235ez",
    text: "235ez",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-234cz",
    text: "234cz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-235dz",
    text: "235dz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-244az",
    text: "244az",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-245az",
    text: "245az",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232hz",
    text: "232hz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232lz",
    text: "232lz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232pz",
    text: "232pz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-132dz",
    text: "132dz",
    unit: "./units/cabin/units/floor_panel.html",
    desc: "./units/cabin/desc/floor_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-132ez",
    text: "132ez",
    unit: "./units/cabin/units/floor_panel.html",
    desc: "./units/cabin/desc/floor_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-132fz",
    text: "132fz",
    unit: "./units/cabin/units/floor_panel.html",
    desc: "./units/cabin/desc/floor_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-132gz",
    text: "132gz",
    unit: "./units/cabin/units/floor_panel.html",
    desc: "./units/cabin/desc/floor_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-242fz",
    text: "242fz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-242dz",
    text: "242dz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232kz",
    text: "232kz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-234dz",
    text: "234dz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-1-actuator",
    text: "1",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-2-actuator",
    text: "2",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-7-actuator",
    text: "7",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-6-actuator",
    text: "6",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-4-actuator",
    text: "4",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-9-actuator",
    text: "9",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-3-actuator",
    text: "3",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-5-actuator",
    text: "5",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-8-actuator",
    text: "8",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-11-actuator",
    text: "11",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-10-actuator",
    text: "10",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-12-actuator",
    text: "12",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-13-actuator",
    text: "13",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-41-actuator",
    text: "41",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-40-actuator",
    text: "40",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-39-actuator",
    text: "39",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-38-actuator",
    text: "38",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-42-actuator",
    text: "42",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-14-actuator",
    text: "14",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-15-actuator",
    text: "15",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-16-actuator",
    text: "16",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-17-actuator",
    text: "17",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-19-actuator",
    text: "19",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-22-actuator",
    text: "22",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-21-actuator",
    text: "21",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-18-actuator",
    text: "18",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-20-actuator",
    text: "20",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-24-actuator",
    text: "24",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-23-actuator",
    text: "23",
    unit: "./units/anvs/units/atva_assy.html",
    desc: "./units/anvs/desc/atva_assy.html",
    info: {},
    access: {},
    show_in_search: true,
  },
];

/**
 * ATVA ACTUATORS R/H SIDE SVG FILE:
 *
 * Path to ATVA Actuators' interactive SVG file from right perspective.
 */
export const SVG_PATH_RH_SIDE = "./apps/anvs/config/atva-actuators/pic/rh-side.svg";

/**
 * ATVA ACTUATORS INTRO FILE:
 *
 * Path to ATVA Actuators' intro HTML file shown at bottom.
 */
export const INTRO_PATH = "./apps/anvs/config/atva-actuators/desc/intro.html";
