/**
 * MICROPHONES ACCELEROMETERS CEILING DATA MODEL:
 *
 * {
 *   id: ID matching the one in the SVG file,
 *   text: text to be used if item is shown in menu,
 *   unit: relative path to unit file on the right,
 *   desc: relative path to desc file on the left,
 *   info: {
 *     path: "./path/to/file.html",
 *     mode: "INLINE" | "POPUP" | "LINK",
 *     title: "Title" (popup only),
 *     size: "size-1" | "size-2" | "size-3" (popup only)
 *   }
 *   access:  {
 *     path: "./path/to/file.html",
 *     mode: "INLINE" | "POPUP" | "LINK",
 *     title: "Title" (popup only),
 *     size: "size-1" | "size-2" | "size-3" (popup only)
 *   },
 *   show_in_search: flag if this item is in search or only in SVG,
 * }
 */
export const DATA_SET_CEILING = [
  {
    id: "clp-56-microphone",
    text: "56",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-57-microphone",
    text: "57",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-52-microphone",
    text: "52",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-53-microphone",
    text: "53",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-54-microphone",
    text: "54",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-49-microphone",
    text: "49",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-70-microphone",
    text: "70",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-71-microphone",
    text: "71",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-72-microphone",
    text: "72",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-55-microphone",
    text: "55",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-60-microphone",
    text: "60",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-58-microphone",
    text: "58",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-59-microphone",
    text: "59",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  
  {
    id: "clp-14-microphone",
    text: "14",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-2-microphone",
    text: "2",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-13-microphone",
    text: "13",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-18-microphone",
    text: "18",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-17-microphone",
    text: "17",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-20-microphone",
    text: "20",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-16-microphone",
    text: "16",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-19-microphone",
    text: "19",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-21-microphone",
    text: "21",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-24-microphone",
    text: "24",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-23-microphone",
    text: "23",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-22-microphone",
    text: "22",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-6-microphone",
    text: "6",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-5-microphone",
    text: "5",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-8-microphone",
    text: "8",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-7-microphone",
    text: "7",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-9-microphone",
    text: "9",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-4-microphone",
    text: "4",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-12-microphone",
    text: "12",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-11-microphone",
    text: "11",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-10-microphone",
    text: "10",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-1-microphone",
    text: "1",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-3-microphone",
    text: "3",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-90-microphone",
    text: "90",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-89-microphone",
    text: "89",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-88-microphone",
    text: "88",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-91-microphone",
    text: "91",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-96-microphone",
    text: "96",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-93-microphone",
    text: "93",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-92-microphone",
    text: "92",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-95-microphone",
    text: "95",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-94-microphone",
    text: "94",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-73-microphone",
    text: "73",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-76-microphone",
    text: "76",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-81-microphone",
    text: "81",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-80-microphone",
    text: "80",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-78-microphone",
    text: "78",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-77-microphone",
    text: "77",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-79-microphone",
    text: "79",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-84-microphone",
    text: "84",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-83-microphone",
    text: "83",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-82-microphone",
    text: "82",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
	{
    id: "clp-245az",
    text: "245az",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-235ez",
    text: "235ez",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-235fz",
    text: "235fz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-235dz",
    text: "235dz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-235cz",
    text: "235cz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-245bz",
    text: "245bz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-245cz",
    text: "245cz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-235bz",
    text: "235bz",
    unit: "./units/cabin/units/ceiling_panel.html",
    desc: "./units/cabin/desc/ceiling_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-244bz",
    text: "244bz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-234cz",
    text: "234cz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-234az",
    text: "234az",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-244cz",
    text: "244cz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-244az",
    text: "244az",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-234dz",
    text: "234dz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-233dz",
    text: "233dz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-233bz",
    text: "233bz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-233cz",
    text: "233cz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-243bz",
    text: "243bz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-243cz",
    text: "243cz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-243az",
    text: "243az",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-233ez",
    text: "233ez",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-234bz",
    text: "234bz",
    unit: "./units/cabin/units/overhead_bin.html",
    desc: "./units/cabin/desc/overhead_bin.html",
    info: {},
    access: {},
    show_in_search: false,
  },
];

/**
 * MICROPHONES ACCELEROMETERS CEILING SVG FROM:
 *
 * Path to Microphones Accelerometers' interactive SVG file from ceiling perspective.
 */
export const SVG_PATH_CEILING = "./apps/anvs/config/microphones-accelerometers/pic/ceiling.svg";

/**
 * MICROPHONES ACCELEROMETERS SIDEWALL DATA MODEL:
 *
 * {
 *   id: ID matching the one in the SVG file,
 *   text: text to be used if item is shown in menu,
 *   unit: relative path to unit file on the right,
 *   desc: relative path to desc file on the left,
 *   info: {
 *     path: "./path/to/file.html",
 *     mode: "INLINE" | "POPUP" | "LINK",
 *     title: "Title" (popup only),
 *     size: "size-1" | "size-2" | "size-3" (popup only)
 *   }
 *   access:  {
 *     path: "./path/to/file.html",
 *     mode: "INLINE" | "POPUP" | "LINK",
 *     title: "Title" (popup only),
 *     size: "size-1" | "size-2" | "size-3" (popup only)
 *   }
 * }
 */
export const DATA_SET_SIDEWALL = [
  
  {
    id: "clp-25-microphone",
    text: "25",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-46-microphone",
    text: "46",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-47-microphone",
    text: "47",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-48-microphone",
    text: "48",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-43-microphone",
    text: "43",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-68-microphone",
    text: "68",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-69-microphone",
    text: "69",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-64-microphone",
    text: "64",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-75-accelerometer",
    text: "75",
    unit: "./units/anvs/units/anvs_accelerometer.html",
    desc: "./units/anvs/desc/anvs_accelerometer.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-74-accelerometer",
    text: "74",
    unit: "./units/anvs/units/anvs_accelerometer.html",
    desc: "./units/anvs/desc/anvs_accelerometer.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-65-microphone",
    text: "65",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-66-microphone",
    text: "66",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-61-microphone",
    text: "61",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-50-microphone",
    text: "50",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-51-microphone",
    text: "51",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-62-microphone",
    text: "62",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-63-microphone",
    text: "63",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-30-microphone",
    text: "30",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-29-microphone",
    text: "29",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-28-microphone",
    text: "28",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-33-microphone",
    text: "33",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-32-microphone",
    text: "32",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-31-microphone",
    text: "31",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-36-microphone",
    text: "36",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-35-microphone",
    text: "35",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-34-microphone",
    text: "34",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-27-accelerometer",
    text: "27",
    unit: "./units/anvs/units/anvs_accelerometer.html",
    desc: "./units/anvs/desc/anvs_accelerometer.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-26-accelerometer",
    text: "26",
    unit: "./units/anvs/units/anvs_accelerometer.html",
    desc: "./units/anvs/desc/anvs_accelerometer.html",
    info: {},
    access: {},
    show_in_search: true,
  },
  {
    id: "clp-67-microphone",
    text: "67",
    unit: "./units/anvs/units/anvs_micro.html",
    desc: "./units/anvs/desc/anvs_micro.html",
    info: {},
    access: {},
    show_in_search: true,
  },
	{
    id: "clp-dato-panel3",
    text: "dato-panel3",
    unit: "./units/cabin/units/dado_panel.html",
    desc: "./units/cabin/desc/dado_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-dato-panel2",
    text: "dato-panel2",
    unit: "./units/cabin/units/dado_panel.html",
    desc: "./units/cabin/desc/dado_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-dato-panel1",
    text: "dato-panel1",
    unit: "./units/cabin/units/dado_panel.html",
    desc: "./units/cabin/desc/dado_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-241hz",
    text: "241hz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-241cz",
    text: "241cz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-231rz",
    text: "231rz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-231nz",
    text: "231nz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-231jz",
    text: "231jz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-231dz",
    text: "231dz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232cz",
    text: "232cz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232ez",
    text: "232ez",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232gz",
    text: "232gz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232hz",
    text: "232hz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232kz",
    text: "232kz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232lz",
    text: "232lz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-242kz",
    text: "242kz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-242fz",
    text: "242fz",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-242az",
    text: "242az",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-232az",
    text: "232az",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
  {
    id: "clp-231az",
    text: "231az",
    unit: "./units/cabin/units/sidewall_panel.html",
    desc: "./units/cabin/desc/sidewall_panel.html",
    info: {},
    access: {},
    show_in_search: false,
  },
];

/**
 * MICROPHONES ACCELEROMETERS SIDEWALL SVG FILE:
 *
 * Path to Microphones Accelerometers' interactive SVG file from sidewall perspective.
 */
export const SVG_PATH_SIDEWALL = "./apps/anvs/config/microphones-accelerometers/pic/sidewall.svg";

/**
 * MICROPHONES ACCELEROMETERS INTRO FILE:
 *
 * Path to Microphones Accelerometers' intro HTML file shown at bottom.
 */
export const INTRO_PATH = "./apps/anvs/config/microphones-accelerometers/desc/intro.html";
